### ISSUE TITLE
I'm not getting notification when app is killed (means background notification not getting)

### ISSUE THREAD

**Issue by Irfanhaidermomin** [rogergcc/ScheduleAlarmWorkManager#1]
How can I resolve?

**Comment by rogergcc** [comment]
weird. 🤔
 This works even when app is killed. 
u have to set date with time and save alarm.
Maybe not work in all devices.
ur device brand, model are u working. ?  
i going to put craslytics later

**Comment by Irfanhaidermomin** [comment]
Redmi note 6 pro.

**Comment by Irfanhaidermomin** [comment]
> weird. 🤔
> This works even when app is killed.
> u have to set date with time and save alarm.
> Maybe not work in all devices.
> ur device brand, model are u working. ?
> i going to put craslytics later

I'm using Redmi note 6 pro.

**Comment by rogergcc** [comment]
> > weird. 🤔
> > This works even when app is killed.
> > u have to set date with time and save alarm.
> > Maybe not work in all devices.
> > ur device brand, model are u working. ?
> > i going to put craslytics later
> 
> I'm using Redmi note 6 pro.

u could try this 
https://stackoverflow.com/questions/48166206/how-to-start-power-manager-of-all-android-manufactures-to-enable-background-and

**Comment by rogergcc** [comment]
in a other hand if want to work when app is reboot in xiaomi 
go to details info of your app and activated auto start or automatic start
